version: '1'
services:
  microservicio:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING.DATASOURCE.URL=jdbc:oracle:thin:@fstack_tp?TNS_ADMIN=/app/wallet_fstack
      - SPRING.DATASOURCE.USERNAME=TienditaUser
      - SPRING.DATASOURCE.PASSWORD=Oraclecloud123
    restart: always